name: f2k
description: Ecommerce app

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+2

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^1.2.2
  flutter_bloc: ^5.0.1
  firebase_auth: ^0.15.2
  firebase_auth_web: ^0.1.1
  google_sign_in: ^4.5.1
  flutter_signin_button: ^1.0.0
  carousel_slider: ^2.2.1
  flutter_staggered_grid_view: ^0.3.0
  animations: ^1.1.2
  hive: ^1.4.1+1
  path_provider: ^1.6.11

  cached_network_image: ^2.2.0+1
  toast: ^0.1.5
  curved_drawer: ^0.1.2
  badges: ^1.1.1

  cupertino_icons: ^0.1.3
  characters: ^1.0.0
  flutter_material_pickers: ^1.7.1
  flappy_search_bar: ^1.7.2
  google_fonts: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.5.1
  build_runner: ^1.10.0
  flutter_launcher_icons: ^0.7.3
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_icons:
  android: 'launcher_icon'
  image_path: 'assets/logo.png'
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Merriweather
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans-Regular.ttf
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
